import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { fileURLToPath } from "node:url";

// EPIC ASTRO (ASTRO-02): the EPIC-R wikis are committed markdown under the repo's
// `feature-doc/` (OUTSIDE frontend/), regenerated by `cdx wiki`. Astro renders
// them NATIVELY (markdown pipeline: headings, tables, code) — retiring the
// hand-rolled `build.render_markdown` → `dangerouslySetInnerHTML` path. The glob
// loader reads them in place (no copy/duplication); they have no frontmatter, so
// no schema. `/wiki/*` pages render them at build time (see pages/wiki/).
const wiki = defineCollection({
  loader: glob({
    pattern: ["FEATURES.md", "wiki/*.md"],
    base: fileURLToPath(new URL("../../feature-doc", import.meta.url)),
  }),
});

// The hand-authored capabilities guide — the human "why & how" companion to the
// machine-generated /wiki. These live under src/content/guides/ and are NOT touched
// by `cdx wiki`; `/guide/*` pages render them at build time (see pages/guide/).
const guides = defineCollection({
  loader: glob({
    pattern: ["*.md"],
    base: fileURLToPath(new URL("./content/guides", import.meta.url)),
  }),
});

export const collections = { wiki, guides };
